name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HATCH_VERSION: "1.7.0"
  PYTHON_VERSION: "3.9"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hatch
        run: pipx install hatch==${{ env.HATCH_VERSION }}

      - name: Set up Python with pip cache
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check Formatting (Black)
        run: hatch run black datalogger_jupyterlab --check

      - name: Lint (Flake8)
        run: hatch run flake8 datalogger_jupyterlab

      - name: Lint (Pylint)
        run: hatch run pylint datalogger_jupyterlab

      - name: Type Check (Mypy)
        run: hatch run mypy datalogger_jupyterlab
