name: Deploy to GitHub Pages

on: workflow_dispatch

env:
  HATCH_VERSION: "1.7.0"
  PYTHON_VERSION: "3.9"
  JUPYTERLAB_DISPLAY_NAME_VERSION: "0.1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hatch
        run: pipx install hatch==${{ env.HATCH_VERSION }}

      - name: Set up Python with pip cache
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build package
        run: hatch build

      - name: Create _site/releases/index.html
        run: |
          mkdir _site
          mkdir _site/releases
          echo '<!DOCTYPE html>
          <html>
            <body>
              <a href="jupyterlab-display-name/">jupyterlab-display-name</a>
            </body>
          </html>' > _site/releases/index.html

      - name: Create _site/releases/jupyterlab-display-name/index.html
        run: |
          mkdir _site/releases/jupyterlab-display-name
          echo '<!DOCTYPE html>
          <html>
            <body>
              <a href="jupyterlab_display_names-${{ env.JUPYTERLAB_DISPLAY_NAME_VERSION }}-py3-none-any.whl">
                jupyterlab_display_names-${{ env.JUPYTERLAB_DISPLAY_NAME_VERSION }}-py3-none-any.whl
              </a>
              <a href="jupyterlab_display_names-${{ env.JUPYTERLAB_DISPLAY_NAME_VERSION }}.tar.gz">jupyterlab_display_names-${{ env.JUPYTERLAB_DISPLAY_NAME_VERSION }}.tar.gz</a>
            </body>
          </html>' > _site/releases/jupyterlab-display-name/index.html

      - name: Move package files into _site/releases/jupyterlab-display-name
        run: mv dist/* _site/releases/jupyterlab-display-name

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
